import { Button } from '@/components';
import Head from 'next/head';
import Link from 'next/link';
import { AiFillGithub } from 'react-icons/ai';

export default function Home() {
  return (
    <>
      <Head>
        <title>Brian Kuhn</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/apple-touch-icon.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/favicon-32x32.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='16x16'
          href='/favicon-16x16.png'
        />
        <link rel='manifest' href='/site.webmanifest' />
      </Head>
      <div className='py-2 text-center text-2xl grid place-content-center'>
        Brian Kuhn
        <p className='text-lg'>Front-end Engineer</p>
        <Button success={true} rounded={true} className='text-base'>
          <Link href='https://github.com/brianslab'>Check out my Github</Link>
        </Button>
      </div>
      <div className='py-2 text-center text-lg underline underline-offset-4'>
        Featured projects:
      </div>
      <div className='flex text-lg py-4 gap-4 text-center place-content-center'>
        <Link href='https://briandkuhn.com'>Portfolio</Link>
        <Link href='https://github.com/brianslab/portfolio'>
          <AiFillGithub />
        </Link>
      </div>
      <div className='flex text-lg gap-4 text-center place-content-center'>
        <Link href='https://rentcalc.briandkuhn.com'>Rent Calculator</Link>
        <Link href='https://github.com/brianslab/rentcalc'>
          <AiFillGithub />
        </Link>
      </div>
    </>
  );
}
